# Site Info
title:              "Blog" # Your site title here
description:        "A blog about science" # Your site description here
google_verify:      abc123 # Put your Google Verification here
google_analytics:   UA-123

# Author Info
author_name:        Uğur Gümüş # Your name here
author_email:       agrogur@gmail.com # Your email here
author_gravatar:    31b93c394e7be48e5574f86ab3bc9fff926945f058a2f8ede65d0e8c41811334 # Your Gravatar md5 hash here for logo

# Site Settings
url:                https://agrogur.github.io
baseurl:            "/blog"
permalink:          /posts/:title # Post permalink
timezone:           Europe/Istanbul
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"

